USE [master]
GO

CREATE SERVER AUDIT SPECIFICATION [ServerAuditSpecification-20210705-204200]
FOR SERVER AUDIT [AuditoriaConvocatoria]
ADD (USER_CHANGE_PASSWORD_GROUP),
ADD (USER_DEFINED_AUDIT_GROUP)
WITH (STATE = ON)
GO


